apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeployXXX
  labels:
    app: autodeployXXX
  namespace: namespace-workflow-1714400516705
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeployXXX
  template:
    metadata:
      labels:
        app: autodeployXXX
    spec:
      containers:
        - name: autodeployXXX
          image: acrworkflow1714400516705.azurecr.io/image-workflow-1714400516705:latest
          ports:
            - containerPort: 5000