apiVersion: v1
kind: Service
metadata:
  name: autodeployXXX
  namespace: namespace-workflow-1714399692718
spec:
  type: LoadBalancer
  selector:
    app: autodeployXXX
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000